# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



Software.create(software_name: 'FreshBooks', subheader: 'Well-Rounded, Intuitive, & Attractive', editor_rating: 4.5, price: '$15/Mo', full_review: 'FreshBooks offers a well-rounded, intuitive, and attractive double-entry accounting experience that supports invoices and estimates, expenses, time tracking, and projects. It anticipates the needs of freelancers and smaller businesses well—better than its competitors.', image_link: 'https://i.pcmag.com/imagery/reviews/01y4SpcWPPMcK3pLVjjSGuo-5.fit_scale.size_1028x578.v_1569478977.jpg')
Software.create(software_name: 'QuickBooks Online', subheader: 'Depth, Flexibility, & Extensibility', editor_rating: 4.5, price: '$20/Mo', full_review: 'QuickBooks Online is still the best online accounting application for small businesses, thanks to its depth, flexibility, and extensibility. It is easy to use, well designed, and built to serve a wide variety of users, but it is also pricey.', image_link: 'https://i.pcmag.com/imagery/reviews/05QRxzQoGBeSmrTCt16cJTU-9..v_1569478652.jpg')
Software.create(software_name: 'Sage 50cloud', subheader: 'Exceptionally Robust & Integrated', editor_rating: 4, price: '$60/Mo', full_review: 'Sage 50cloud is an exceptionally robust small business desktop accounting application, incorporating a comprehensive set of financial tools and generous customization options. New integration with Microsoft Office 365 makes it a hybrid solution: local, hard drive-based software that can share data with productivity applications via the cloud.', image_link: 'https://financesonline.com/uploads/2014/10/Sage_50cloud.png')
Software.create(software_name: 'Zoho Books', subheader: 'Exceptional Interface & Great Pricing', editor_rating: 4, price: '$9/Mo', full_review: 'Zoho Books is an excellent choice for cloud-based small business accounting, with an exceptional interface, an attractive price, and a rich set of tools. Its limited payroll offering may cause some users to look elsewhere, however.', image_link: 'https://i.pcmag.com/imagery/reviews/036rJcAK3sZYpCdHStxxy8U-9.fit_scale.size_1028x578.v_1574731283.jpg')
Software.create(software_name: 'Wave', subheader: 'Great Free Option', editor_rating: 4, price: '$19/Mo', full_review: 'Wave is priced like a freelancer accounting application (it is free), and it is an excellent service for that market. But it also offers enough extras that a small business with employees could use it—with some caveats.', image_link: 'https://i.pcmag.com/imagery/reviews/05RZ9kt20hRmvereS8C4BVz-5.fit_scale.size_1028x578.v_1569471498.png')
Software.create(software_name: 'Xero', subheader: 'Good Reconciliation, Imports & Inventory', editor_rating: 4, price: '$60/Mo', full_review: 'Small business accounting website Xero has strengths in many areas, like account reconciliation, data imports, inventory management, and project tracking. Recent improvements in areas like reports, projects, and document management make it one of the top choices for todays small businesses.', image_link: 'https://i.pcmag.com/imagery/reviews/00sBaEC1FgxzEuHTEMs1ANy-9.fit_scale.size_1028x578.v_1569473928.jpg')
Software.create(software_name: 'Kashoo', subheader: 'Usability, Support & Speed', editor_rating: 3.5, price: '$20/Mo', full_review: 'Kashoos strengths are income and expense management, usability, and support. It is a simple, speedy choice for smaller businesses that do not need product inventory tracking or robust time billing tools.', image_link: 'https://i.pcmag.com/imagery/reviews/024wkW6JGWbWEKLQPN48OmK-9..v_1569477615.jpg')
Software.create(software_name: 'Sunrise', subheader: 'Great for Freelancers & Sole Props', editor_rating: 3.5, price: '$15/Mo', full_review: 'Sunrises combination of tools and usability make it a good choice for freelancers and sole proprietors who need to track income, expenses, and invoice customers. It lacks some features that microbusinesses might use, though, like time tracking and full mobile access.', image_link: 'https://i.pcmag.com/imagery/reviews/062SFGcRVHqk6sxr9m70oaV-7.fit_scale.size_1028x578.v_1574731157.png')
Software.create(software_name: 'QuickBooks Self-Employed', subheader: 'Simplified Choice for Contractors', editor_rating: 3, price: '$15/Mo', full_review: 'QuickBooks Self-Employed will appeal to freelancers and independent contractors who want its automatic mileage tracking, quarterly tax estimating, and basic bookkeeping. Businesses that need features like time tracking, sales tax, robust invoices, and data records should consider QuickBooks Online.', image_link: 'https://i.pcmag.com/imagery/reviews/005hsRHZ8Vnt44cCV11e8fV-7.fit_scale.size_1028x578.v_1569478564.jpg')
Software.create(software_name: 'GoDaddy Bookkeeping', subheader: 'Integration with Amazon, eBay & Etsy', editor_rating: 3.5, price: '$5/Mo', full_review: 'GoDaddy Bookkeepings direct integration with Amazon, eBay, and Etsy make it a terrific tool for entrepreneurs who sell at those sites. Its overall bookkeeping depth and flexibility are good, and it is easy to use. But it lacks much of FreshBooks functionality.', image_link: 'https://i.pcmag.com/imagery/reviews/06DahDjNzUbKfgP3YSn7z7n-7.fit_scale.size_1028x578.v_1580315575.png')




